![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

# <b> Práctica Clase 3 </b> <br>

## <b> Numpy </b>

In [1]:
import numpy as np

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## <b> Ejercicio 1 </b>

*   Ítems a resolver: <br>

    1)  ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda. <br>

    2)  ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda. <br>

    3)  ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta. <br>

### <b> Resolución </b>

1.  ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda. <br>

    ![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

*   A partir de una lista podemos crear un arreglo de numpy

In [2]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


*   Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [3]:
arreglo = np.arange(8)
print(arreglo)

[0 1 2 3 4 5 6 7]


2)  ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda. <br>

    ![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

*   Algunas cosas que se pueden hacer con arreglos pero no con las listas:

    a)  Sumarle un mismo elemento

In [4]:
print(lista + 1)

TypeError: can only concatenate list (not "int") to list

In [5]:
arreglo = arreglo + 1

In [6]:
print(arreglo)
arreglo.shape

[1 2 3 4 5 6 7 8]


(8,)

*   Algunas cosas que se pueden hacer con arreglos pero no con las listas: <br>

    b)  Elevar al cuadrado todos los elementos

In [7]:
print(lista**2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [8]:
print(arreglo**2)

[ 1  4  9 16 25 36 49 64]


*   Algunas cosas que se pueden hacer con arreglos pero no con las listas: <br>

    c)  Sumar todos los elementos

In [9]:
print(arreglo.sum())
print(lista.sum())

36


AttributeError: 'list' object has no attribute 'sum'

In [10]:
n = 0
for e in lista:
    n = n + e
print(n)

15


In [11]:
arreglo.shape

(8,)

In [12]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (3, 6) 



<b> Nota: </b> Los corchetes adicionales corresponde a la dimensión más externa, y se lee (para este caso); shape = (filas, colimnas) 

In [ ]:
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

In [ ]:
arreglo = np.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

<b> Nota: </b> '.T' devuelve la transpuesta.

3)  ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta. <br>

    *   <b> Para (n,): </b> Se trata de un arreglo unidimensional conocido como vector renglon, para python la estructra que almacena los datos unicamente posee una dimensión (una fila). <br>

    *   <b> Para (n,1): </b> Se trata de un arreglo unidimensional conocido como vector columna, para python la estructra que almacena los datos unicamente posee una columna y enesimas filas.    

    *   <b> Para (1,n): </b> Se trata de un arreglo unidimensional conocido como vector renglon, para python la estructra que almacena los datos unicamente posee una fila y enesimas columnas.

    ![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

In [23]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (2,n)')
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto

print('Arreglo de (1,n)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")


Arreglo de (n,)
[1 2 3 4 5 6] . Shape = (6,) 

Arreglo de (2,n)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (2, 6) 

Arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 

Arreglo de (1,n)
[[1 2 3 4 5 6]] . Shape = (1, 6) 



In [21]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]] . Shape = (6, 2)


<b> Nota: </b> <br>

*   En los corchetes internos se añaden más columnas al arreglo. <br>
*   En los corchetes externos se añaden más filas al arreglo. <br>
*   Debe haber homogeneidad en el número de columnas en las filas del arreglo.



In [24]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a1.shape

(2, 4)

In [25]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2.shape

(2, 4)

In [26]:
a3 = a1 * a2
a3.shape

(2, 4)

In [27]:
a3

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## <b> Ejercicio 2 </b>

*   Ítems a resolver:

    1)  Escribir un arreglo con números enteros del 0 al 9. Pista: arange <br>

    2)  Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace <br>

### <b> Resolución </b>

1)  Escribir un arreglo con números enteros del 0 al 9. Pista: arange <br>

    ![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

2)  Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace <br>

    ![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## <b> Ejercicio 3 </b>

*   Ítems a resolver: <br>

    1)  Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
    Pista: mask <br>

### <b> Resolución </b>

1)  Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask <br>

    ![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## <b> Ejercicio 4 </b>

*   Ítems a resolver: <br>

    1)  Crear un arreglo de ceros de `shape` (5,10). <br>

    2)  Reemplazar la segunda y cuarta fila con unos. <br>

    3)  Reemplazar la tercera y octava columna con dos (2). <br>


### <b> Resolución </b>

1)  Crear un arreglo de ceros de `shape` (5,10). <br>


    ![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

2)  Reemplazar la segunda y cuarta fila con unos. <br>



    ![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

3)  Reemplazar la tercera y octava columna con dos (2). <br>


    ![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## <b> Recursos </b> 


*   Hacer todos los ejercicios que puedan de los siguientes links: <br>

    *   https://www.machinelearningplus.com/python/101-numpy-exercises-python/ <br>

    *   https://github.com/rougier/numpy-100 <br>

*   Para explorar las funciones de creación de datos aleatorios: <br>

    *   https://numpy.org/doc/stable/reference/random/legacy.html

In [ ]:
a = np.random.random((4,2,3)) * 100 + 100
a

In [ ]:
a = np.random.random((4,4))

In [ ]:
a

In [ ]:
a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=np.int8)

In [ ]:
a

In [ ]:
a.sum()

In [ ]:
a.std()

In [ ]:
a.sort(axis=1)

In [ ]:
a

In [ ]:
a.sort(axis=0)
a

In [ ]:
a[1:3,0:3]

In [ ]:
l =   [[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]]

In [ ]:
a = np.array([l])

In [ ]:
a.shape

In [ ]:
a.reshape(24)

In [ ]:
a = np.matrix([[1,2,3,4,5,6]]) 
print(a) 

In [ ]:
b = np.matrix([[1],[2],[3],[4],[5],[6]]) 
print(b) 

In [ ]:
c = a * b 
print(c) 

In [ ]:
d = b * a 
print(d)